# _config.yml for staticsite

## directory configuration
source:         .
destination:    ./public
layouts:        ./layouts
data_source:    ./data

# blog settings
timezone:       America/New_York
highlighter:    pygments
permalink:      pretty
paginate:       10
paginate_path:  '/blog/:num'
markdown:       redcarpet
safe:           true

## excludes
exclude:        ['.csscomb.json', '.editorconfig', '.env', '.env.sample', '.gitignore', '.gitkeep', '_config.yml', 'aws-credentials.json', 'blog/_posts/partials', 'blog/partials', 'build.json', 'composer.json', 'composer.lock', 'data/', 'fonts/', 'Gulpfile.js', 'images/', 'layouts/', 'node_modules/', 'npm-debug.log', 'package.json', 'partials/', 'readme.md', 'README.md', 'scripts/', 'source/', 'styles/', 'todo.md', 'TODO.md', 'vendor/']

## development server settings
host:           127.0.0.1
port:           4000
url:            http://127.0.0.1 # change to production domain
baseurl:        /

## extension settings
redcarpet:
  extensions: ['smart']

## meta data
author:         "Emerson Media"
title:          "Static Site"
description:    "TODO:"
keywords:       "TODO:"

## use the 'links' array to set up commonly used links, such as:
## `example: "/example/"` here can be used as {{ site.links.example }} in Liquid
links:
    dashboard:           "/dashboard/"
    users:           "/users/"
    feed:           "/rss.xml"
    sitemap:        "/sitemap.xml"
    style-guide:    "/style-guide/"

    # add site specific links below:
    example:        "/example/"
